package mwasi:noise-demo@0.1.0;

package mwrapper:crypto@0.1.0 {
//    interface crypto {

//        resource buffer {
//            constructor();
//            update: func(input: list<u8>);
//            finalize: func() -> list<u8>;
//            reset: func();
//            finalize-reset: func() -> list<u8>;
//        }
//    }
   // Monitor hooks
   interface monitorkey {

    mon-setup-static: func(ltk: list<u8>);
    mon-init-peer: func(ltk: list<u8>, pk-r: list<u8>); 
//     mon-exp-g-from-priv: func(ltk: list<u8>);
//     mon-dh-shared: func(peer-pk: list<u8>, my-priv: list<u8>);
//     mon-rand: func(n: list<u8>);

     mon-exp-g-pair: func(ltk: list<u8>, expgltk: list<u8>);
//     mon-hash-pair: func(proto: string, digest32: list<u8>);
//     mon-precompute: func(ltk: list<u8>);
//     mon-hpair-pk-r: func(label: list<u8>, rhs-pk-r: list<u8>);
//     mon-hpair-expgltk-i: func(label: list<u8>, rhs-expgltk-i: list<u8>);
//     mon-hpair-proto-identifier: func(digest32: list<u8>, identifier: string);
//     mon-exp-gr-pair: func(n: list<u8>, rhs-expgr: list<u8>);
//     mon-ephemeral-exp-from-rand-tag: func(n: list<u8>);
//     mon-hmac-cii-expgr: func(cii-digest32: list<u8>);
//     mon-exppk-r: func(pk-r: list<u8>, r: list<u8>);
//     mon-hmac-ciiexpgr-type1: func();
//     mon-hpairhipk-r: func(pk-r: list<u8>);
//     mon-hmac-hmachmacciiexpgr0x01-exppkrr: func();
//     mon-hmac-hmachmachmacciiexpgr0x01-exppkrr0x01: func();
//     mon-hmac-hmachmachmachmacciiexpgr0x01-exppkrr0x01-bytes: func(sisr: list<u8>);
//     mon-hmac-hmachmachmachmacciiexpgr0x01-exppkrr-pair0x02: func();
//     mon-h-of-pair-hpairhipk-r-and-expgr: func();
//     mon-hmac-hmachmachmachmacciiexpgr0x01-exppkrr0x01sisr0x01: func();
//         // --- NEW ---
//     // -> Rust name: mon_hmac_hmachmachmachmacciiexpgr0x01_exppkrr0x01sisr_pair0x02()
//     mon-hmac-hmachmachmachmacciiexpgr0x01-exppkrr0x01sisr-pair0x02: func();

//     // -> Rust name: mon_aead_pair0x02_zero_nonce_expgltk_i(expgltk_i: Vec<u8>)
//     mon-aead-pair0x02-zero-nonce-expgltk-i: func(expgltk-i: list<u8>);
//      // -> Rust name: mon_h_of_pair_hpairhpairhipk_rexpgr_and_prev_aead()
//      mon-h-of-pair-hpairhpairhipk-rexpgr-and-prev-aead: func();

//      mon-aead-sisr-pair0x02-zero-nonce-ts-with-h3-ad: func(ts: list<u8>);


//   // NEW (for Handshake_Init_2 triggers):
//   // h(⟨hi0, ats⟩) -> "hpairhi0ats"  (ts is needed to reconstruct ats)
//   mon-hpair-hi0-ats: func(ts: list<u8>);
//   // h(⟨⟨sidI,pekI⟩,⟨astat,ats⟩⟩) -> "hpairsidIpekIastatats"
//   mon-hpair-sidi-peki-astat-ats: func(sid-i: list<u8>, pek-i: list<u8>, astat: list<u8>, ts: list<u8>);
    mon-hash: func(preimage: list<u8>, digest: list<u8>);
  }
}

world noise-demo {
  // import mwrapper:crypto/crypto@0.1.0;
   import mwrapper:crypto/monitorkey@0.1.0;

}